Django_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('final4/', include('final4.urls')),
    path('admin/', admin.site.urls),
    path('', include('single_pages.urls')), # 없으면 싱글페이지 url로 가라
    path('blog/', include('blog.urls')),
    path("accounts/", include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 묶어줘라는 뜻 이주소는이제 ==> _media폴더로 간다.

blog/urls.py
from django.urls import path
from . import views # 블로그에 있는 view를 import

urlpatterns = [
    # path('', views.index), # 블로그에 들어와서 아무것도 치지 않았다면 view의 index를 보여줘라, server/blog/ 까지 온상태임, 만약에 /이거 붙이면 ==> server/ 이렇게로 바뀜 # '' 그냥 아무것도 안써야, server/blog/를 타고 왔기에 이주소로 남겨져 있음.
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('', views.PostList.as_view()), #views.PostList쓰면 자동으로 가져옴 # 근데 이거는 클래스라 동작으로 못해 # 그래서 함수를 호출해준다 as_view
    path('<int:pk>/new_comment/', views.new_comment), #/blog/1/new_comment/
    path('update_comment/<int:pk>/',views.CommentUpdate.as_view()),# ex) /blog/update_comment/2
    path('delete_comment/<int:pk>/', views.delete_comment),# ex) /blog/delete_comment/2

    path('<int:pk>/', views.PostDetail.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),

    # path('<int:pk>/', views.single_post_page), #pk라는 정수가 1개 들어온다는 뜻,
        # 프라이머리키에 따라서 보여주는 화면을 다르게 할꺼임
        # 따라서 views에 pk라는 전달인자를 1개 씀
        # def single_post_page(request, pk):
        # 정수가 들어오면 무조건 이렇게 됨

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# 다대다 관계
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name # pk:고유번호

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name # pk:고유번호

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Categories'

class Post(models.Model):
    title = models.CharField(max_length=30)# 30글자까지 title가능,char형으로
    hook_text = models.CharField(max_length=100, blank=True) # blank는 옵션
    content = models.TextField()# 넓게 쓸 수 있는 공간

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True) # 년,월,일로 구분해서 구분하겠다.

    created_at = models.DateTimeField(auto_now_add=True) # auto_now_add=True==> 현재시간 자동 추가
    update_at = models.DateTimeField(auto_now=True) # 자동 입력

    # author
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL) # 이 사람과 연관된거 모두 제거 # on_delete=nodels.SET_NULL, on_delete=nodels.CASCADE
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    # manytomany ==> 다대다관계
    tags = models.ManyToManyField(Tag, blank=True) # 없으면 자동으로 null이 됨, 그래서 안해도됨

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}' #pk:고유번호

    def get_absolute_url(self):
        return f'/blog/{self.pk}/' # blog밑에 자동적으로 주소 뒤에 붙은 걸 호출한다.

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'
    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

blog/forms.py
from .models import Comment
from django import forms
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post, Category, Comment # 데이터 베이스를 접근하기 위해
from django.core.exceptions import PermissionDenied
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q

def csrf_failure(request, reason=""):
    return redirect('/blog/')

class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView): # form을 지원한다.
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category', 'tags']

    # default template_name => post_form.html
    # template_name = 'blog/post_form.html'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff
        # superuser나 스태프이상의 레벨이 있을 때, 글을 작성할 수 있도록, 일반유저는 안됨(아이디없는사람)
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user # 맞을경우, 현재 사용자명을 그대로 사용자한테 넣어준다.
            # not tag
            return super(PostCreate, self).form_valid(form) # form내용을 검증하는 상위 클래스로 보내준다.
        else:
            return redirect('/blog/') # 그렇지 않을겨우, 아무유저도 아니면, blog url로 다시 리다이렉션 시켜버린다.

class PostList(ListView): # 모델명: post_list.html, post_list라는 변수를 자동으로 넘겨줌
    model = Post
    ordering = '-pk'
    paginate_by = 2 # page마다 post 몇개 보여 줄 지

    # 추가 context-Category
    # 글 전부를 담아서 넘김
    def get_context_data(self, **kwargs): # template쪽으로 context가 넘어감
        context = super(PostList, self).get_context_data() # post_list
        context['categories'] = Category.objects.all() # 카테고리들을 저장함
        context['no_category_post_count'] = Post.objects.filter(category=None).count() # 분류되지 않는 카테고리에다가, 숫자를 저장함
        return context # -> post_list.html {post_list, categories, no_category_post_count}
class PostDetail(DetailView): # 모델명: post_detail.html, post라는 변수를 자동으로 넘겨줌
    model = Post
    # template_name = 'blog/single_post_page.html'
    # post라는 변수에 1개만 넘김
    def get_context_data(self, **kwargs):  # template쪽으로 context가 넘어감
        context = super(PostDetail, self).get_context_data()  # post_list
        context['categories'] = Category.objects.all()  # 카테고리들을 저장함
        context['no_category_post_count'] = Post.objects.filter(category=None).count()  # 분류되지 않는 카테고리에다가, 숫자를 저장함
        context['comment_form'] = CommentForm
        return context  # -> post_list.html {post, categories, no_category_post_count}

def category_page(request, slug):
    if slug == 'no_category': #/blog/category/no_category/
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else: # /blog/category/slug (프로그래밍, 문화-예술 등등)
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    # return으로 위에서 일부골라낸것만 보내고, 그리고 내가 원하는거 추가해서 보낸다.
    return render(
        request,
        'blog/post_list.html',
        {
            'post_list': post_list,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
            'category': category, # 현재 분류에 대한 이름을 추가해서 보냈음. 지금 무슨 카테고리인지 알 수 있도록
        }
    )

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category', 'tags']

    template_name= "blog/post_update_form.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk) # Post.objects.filter 현재 pk만 가져온다

        if request.method == "POST":
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
            else:
                return redirect(post.get_absolute_url())
        else:
            raise PermissionDenied # 로그인안된 상태에서 접근하려하면 승인에러

def delete_comment(request, pk):
    # Commnet라는 모델을 가져온 적이 없기에, 가져와야함
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment  # 자동으로 댓글 수정 폼에 내용 채워라?
    form_class = CommentForm
    # comment_form.html -> 이걸 자동으로 찾음. 안 만들면, 못 찾는다고 에러 뜸!

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

# ListView에서 자동으로 이런것들을 전부 상속받았음
# class PostList(ListView): model=Post(Post.objects.all) # post_list.html
# def get_queryset(self):
#       post_list=Post.objects.all  이렇게됌.

class PostSearch(PostList):  # post_list.html
    paginated_by = None  # pagination 안하겠다

    def get_queryset(self):  # Post(Post.objects.all) 이게 불러와진다
        q = self.kwargs['q']
        post_list = Post.objects.filter(Q(title__contains=q) | Q(tags__name__contains=q)).distinct()
        return post_list

    def get_context_data(self, **kwargs): # 검색한 결과를 보여주기 위해서
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q'] # 검색어를 가져온다.
        context['search_info'] = f'Search:{q}({self.get_queryset().count()})'
        # search_info라는 값에다가 문자열을 넣어서 보내라, 추가적인 context, 전체 쿼리셋

        return context







# def index(request):
#     posts = Post.objects.all().order_by('-pk')
#     # posts = Post.objects.all() # objects 하면 여기에 실제로 들어있는 데이터
#                                 # get, lastm first, all등을 통해서 원하는 데이터를 가져 올 수 있다.
#                                 # 리스트 형식으로 가져옴
#                                 # 이때가 데이터베이스를 가져오는 순간이다.
#                                 # 그래서 가져올 때 쿼리를 날려서
#                                 # pk를 역순으로 가져오기
#     return render(
#         request,
#         'blog/post_list.html', # 함수명이랑 html이랑 이름 안같아도 됨 자유
#         {
#             'posts':posts,
#         } # 데이터를 넘길 때 json형식으로, index.html에게 넘기기, index로 가셈 이제, 확인
#     )

# def single_post_page(request, pk):
#     post = Post.objects.get(pk=pk) # 전달인자로 pk가 오면 여기에 해당하는 post 1개만 가져오기
#                                     # select에 조건문을 달아주는 개념임
#                                     # 이제 post를 넘겨줘야 한다.
#                                 # 넘겨주는 방법은?
#                                 # 밑에처럼 json형식으로 넘겨준다.
#     return render(
#         request,
#         'blog/single_post_page.html',
#         {
#             'post':post,
#         }
#     )

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'blog/bootstrap4/css/bootstrap.min.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/89a12d4a7e.js" crossorigin="anonymous"></script>

</head>
<body>

    {% include 'blog/navbar.html' %}

    <!-- main content -->
    <div class="container my-4">
        <div class="row">
<!--            <div class="col-md-8 col-lg-9">-->
            <div class="col-sm-8" id="main-area">
                {% block main_content %}

                {% endblock %}
            </div>

<!--            <div class="col-md-4 col-lg-3">-->
            <div class="col-sm-4">
                <!-- Search widget-->
                <div class="card mb-4">
                    <div class="card-header">Search</div>
                    <div class="card-body">
                        <div class="input-group">
                            <input id="search-input" class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                            <button onclick="searchPost();" class="btn btn-primary" id="button-search" type="button">Go!</button>
                        </div>
                    </div>
                </div>
                <!-- Categories widget-->
                <div class="card mb-4" id='categories-card'>
                    <div class="card-header">Categories</div>
                    <div class="card-body">
                        <div class="row">

                                <ul>
<!--                                    {{ no_category_post_count }}-->
                                    {% for category in categories %}
                                    <li>
                                        <a href="{{ category.get_absolute_url }}"> {{ category }} ({{ category.post_set.count}})
                                        </a>
                                    </li>
                                    {% endfor %}
                                    <li>
                                        <a href="/blog/category/no_category/">미분류 ({{ no_category_post_count }})</a>
                                    </li>
<!--                                    <li><a href="#!">프로그래밍 (2)</a></li>-->
<!--                                    <li><a href="#!">문화 & 예술 (2)</a></li>-->
<!--                                    <li><a href="#!">미분류 (2)</a></li>-->
                                </ul>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'blog/footer.html' %}

    <!-- 해당하는 id먼저 가져오고 그다음에 값을 가져온다. trim()은 앞뒤공백을 짤라서 문자열만 가져옴-->
    <script>
        function searchPost(){
            let searchValue = document.getElementById("search-input").value.trim();
            if( searchValue.length > 1) {
                location.href = "/blog/search/"+ searchValue + "/";
            }
            else{
                alert("검색어(" + searchValue + ")가 너무 짦습니다.");
            }
        };
        document.getElementById("search-input").addEventListener("keyup", function(event){
        if(event.key === "Enter")
        {
            searchPost();
        }

        });

    </script>
<!-- enter면 searchPost함수호출-->
</body>
</html>

blog/templates/blog/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'blog/bootstrap4/css/bootstrap.min.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

    <script src="https://kit.fontawesome.com/89a12d4a7e.js" crossorigin="anonymous"></script>

</head>
<body>

    {% include 'blog/navbar.html' %}

    <!-- main content -->
    <div class="container my-4">
        <div class="row">
<!--            <div class="col-md-8 col-lg-9">-->
            <div class="col-sm-12" id="main-area">

                {% block main_content %}
                {% endblock %}

            </div>


        </div>
    </div>

    {% include 'blog/footer.html' %}

</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Comment Post - Blog{% endblock %}

{% block main_content %}
    <h1>Edit Comment</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}

blog/templates/blog/footer.html
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
    </footer>

blog/templates/blog/post_detail.html
            {% extends 'blog/base.html' %}
            {% load crispy_forms_tags %}

            {% block head_title %}
                {{ post.title }} - Blog
            {% endblock %}

            {% block main_content %}

                <!-- Post content-->
                <article>
                <div id="post-area">
                    <!-- Post header-->
                    <header class="mb-4">
                        <!-- Post title-->
                        <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
                        <h5 class="text-muted">{{ post.hook_text }}</h5>
                        <!-- Post meta content-->
                        <div class="text-muted fst-italic mb-2">Posted on {{ post.created_at }}
                            by <a href="#">{{ post.author | upper }}</a></div>


                        <!-- edit button-->
                        {% if user.is_authenticated and user == post.author %}
                         <a class="btn btn-info btn-sm float-right" href="/blog/update_post/{{ post.pk }}" role="button">
                            <i class="fas fa-pen"></i>&nbsp;&nbsp;Edit Post
                         </a>
                        {% endif %}

                        <!-- Post categories-->
                        {% if post.category %}
                            <span class="badge badge-secondary"> {{ post.category }} </span>
                        {% else %}
                            <span class="badge badge-secondary">미분류</span>
                        {% endif %}

                    </header>
                    <!-- Preview image figure, 만약 이미지 있으면 보여주고, 없으면 random image-->
                    <figure class="mb-4">
                        {% if post.head_image %}
                            <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }} head image" />
                        {% else %}
                            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{post.id}}/800/200" alt="random image" />
                        {% endif %}
                    </figure>

                    <!-- Post content, post에 해당하는 글 적기-->
                    <section class="mb-5">
                        <p class="fs-5 mb-4">{{ post.content | linebreaksbr }}</p>

                        <!--tag area tag적혀있는곳, 링크는 아니고 태그들 for문으로 나열-->
                        {% if post.tags.exists %}
                            <i class = "fas fa-tags"></i>
                            {% for tag in post.tags.all %}
                                <span class="badge badge-pill badge-light">{{ tag }}</span>
                            {% endfor %}
                        <br /><br />
                        {% endif %}

                        {% if post.file_upload %}
                            <a href="{{ post.file_upload.url }}" class="btn btn-outline-dark" role="button" download>Download:
                            {% if post.get_file_ext == 'csv' %}
                                <i class="fas fa-file-cvs"></i>
                            {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                                <i class="fas fa-file-excel"></i>
                            {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                                <i class="fas fa-file-word"></i>
                            {% else %}
                                <i class="fas fa-file"></i>
                            {% endif %}
                            {{ post.get_file_name }}
                            </a>
                        {% endif %}
                    </section>
                </div>
                </article>

                <!-- Comments section-->
                <section class="mb-5">
                <div id="comment-area">
                    <div class="card bg-light">
                        <div class="card-header">Leave a Comment</div>
                        <div class="card-body">
                            {% if user.is_authenticated %}

                            <!-- Comment form-, 새로운 댓글 적는곳-->
                            <form class="mb-4" id="comment-form" method="POST" action="{{ post.get_absolute_url }}new_comment/">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ comment_form | crispy }}
                                </div>
                                <button type="submit" class="btn btn-primary float-right">Submit</button>
                            </form>
                            {% else %}
                                <a role="button" class="btn-outline-dark btn-block btn-sm"
                                   href="#" data-toggle="modal" data-target="#loginModal">Log In and leave a comment</a>

                            {% endif %}
                            </div>
                        </div>

                        <div class="card">
                            <div class="card-body">
                            {% if post.comment_set.exists %}
                            {% for comment in post.comment_set.iterator %}
                            <!-- Single comment-->
                            <div class="d-flex mb-4" id="comment-{{ comment.pk }}">
                                     <div class="flex-shrink-0"> <img class="rounded-circle"
                                                    src="https://dummyimage.com/50x50/ced4da/6c757d.jpg&text={{comment.author}}"
                                                    alt="..."/>
                                </div>

                                <div class="ms-3"> <!-- <div class="media-body"> -->
                                    <!-- 만약 로그인아이디랑 일치하면 edit, delete버튼 생김-->
                                    {% if user.is_authenticated and comment.author == user %}
                                    <div class="float-right">
                                    <a role="button" class="btn btn-sm btn-info"
                                        id="comment-{{comment.pk}}-update-btn"
                                        href="/blog/update_comment/{{comment.pk}}/">
                                        <small>edit</small>
                                    </a>
                                    <a role="button" class="btn btn-sm btn-danger"
                                       id="comment-{{comment.pk}}-delete-btn"
                                       href="/blog/delete_comment/{{comment.pk}}/">
                                        <small>delete</small></a>
                                </div>
                                    {% endif %}

                                    <!-- 댓글중에 이름,시간 -->
                                    <span class="fw-bold">
                                        {{ comment.author.username }} &nbsp;&nbsp;<small class="text-muted">{{comment.created_at}}</small>
                                    </span>
                                    <!-- 글자 cntent -->
                                    <div> {{ comment.content | linebreaks }}</div>

                                    <!-- 시간 update되었을 때, update 시각 -->
                                    {% if comment.created_at != comment.modified_at %}
                                        <p class="text-muted float-right"><small>Updated: {{ comment.modified_at }}</small></p>
                                    {% endif %}

                                </div>
                            </div>
                            {% endfor %}
                            {% endif %}
                   </div>
                </div>
            </div>
        </section>

            {% endblock %}

blog/templates/blog/post_form.html
    {% extends 'blog/base_full_width.html' %}

    {% load crispy_forms_tags %}

        {% block head_title %}Create Post - Blog{% endblock %}

    {% block main_content %}

    <h1>Create New Post</h1>
    <hr />
    <form method = "post" enctype="multipart/form-data">{% csrf_token %}
            {{ form | crispy }}
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
        {% endblock %}

blog/templates/blog/post_list_old.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>blog</title>
</head>
<body>
    <nav>
        <a href="/">HOME</a>
    </nav>
    <h2>post list</h2>

<!--    for p in posts --> <!-- 1. 스스로 만들때-->
    {% for p in post_list %} <!-- 2. post 클래스를 이용할때, 안 지정해주면 post_list 모델명 list로 바꿔줘야 제대로 받아옴-->
    <hr />
<!--    <h3><a href="{{ p.pk }}/">{{ p.title }} </a></h3>-->
    <h3><a href="{{ p.get_absolute_url }}">{{ p.title }} </a></h3> <!-- 이 함수를 부르면 그 주소를 반환-->
    <p>{{p.created_at}}</p>
    <p>{{p.content}}</p>  <!--  필드를 가져옴 -->
    <!--    <h3>{{ p }} </h3>
    <h3>{{ p.pk }} </h3> -->

    {% endfor %}

</body>
</html>

blog/templates/blog/post_update_form.html
    {% extends 'blog/base_full_width.html' %}

    {% load crispy_forms_tags %}

        {% block head_title %}Edit Post - Blog{% endblock %}
    {% block main_content %}

    <h1>Edit Post</h1>
    <hr />
    <form method = "post" enctype="multipart/form-data">{% csrf_token %}

       {{ form | crispy }}

        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>

    {% endblock %}